[workspace]
members = [
    "src/nr/immutables_contract",
    "src/nr/schnorr_account_contract",
    "src/nr/schnorr_initializerless_account_contract",
]

[benchmark]
account = "benchmarks/account.benchmark.ts"
immutables = "benchmarks/immutables.benchmark.ts"
schnorr_initializerless_account = "benchmarks/schnorr_initializerless_account.benchmark.ts"
account_counter_comparison = "benchmarks/account_counter_comparison.benchmark.ts"
