[workspace]
members = [
    "src/nr/constants_contract",
    "src/nr/schnorr_account_contract",
    "src/nr/schnorr_constants_account_contract",
]

[benchmark]
account = "benchmarks/account.benchmark.ts"
