[workspace]
members = [
    "src/nr/counter_contract",
    "src/nr/constants_contract",
    "src/nr/schnorr_account_contract",
    "src/nr/schnorr_initializerless_account_contract",
]

[benchmark]
counter = "benchmarks/counter.benchmark.ts"
constants = "benchmarks/constants.benchmark.ts"
schnorr_initializerless_account = "benchmarks/schnorr_initializerless_account.benchmark.ts"
account_counter_comparison = "benchmarks/account_counter_comparison.benchmark.ts"
