[package]
name = "immutables_contract"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v5.0.0-nightly.20260612", directory = "aztec" }
immutables = { path = "../immutables" }
