[package]
name = "schnorr_initializerless_account_contract"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.2.0", directory = "noir-projects/aztec-nr/aztec" }
schnorr = { tag = "v0.2.0", git = "https://github.com/noir-lang/schnorr" }
immutables = { path = "../immutables" }